In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("data2.csv", index_col=0)

In [8]:
df.head()

,Diagnosis,OR4F5,AL627309.1,OR4F29,OR4F16,AL669831.1,AL645608.2,SAMD11,NOC2L,KLHL17,...,MT-CO2,MT-ATP8,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,MT-ND4,MT-ND5,MT-ND6,MT-CYB
SEQ12179,0,5.181797,6.179015,4.727253,4.727253,5.181797,4.727253,6.448955,6.668955,6.348396,...,5.181797,4.727253,4.727253,4.727253,4.727253,4.727253,4.727253,4.727253,4.727253,5.181797
SEQ12182,1,4.727253,6.085531,5.102764,5.256828,5.374064,5.634632,6.291008,6.558533,6.039314,...,4.727253,4.727253,4.727253,4.727253,4.727253,4.727253,5.102764,4.727253,4.727253,5.374064
SEQ12199,0,5.236380,7.428169,5.349217,5.443627,5.236380,5.236380,6.733031,7.013539,6.756903,...,4.727253,4.727253,4.727253,5.526190,4.727253,4.727253,5.236380,4.727253,4.727253,5.236380
SEQ12196,1,5.145956,6.904024,5.145956,4.727253,5.210170,5.266549,6.653595,6.986734,6.698891,...,4.969556,4.727253,4.727253,4.727253,4.727253,4.727253,4.727253,4.969556,4.727253,5.069520
SEQ12201,0,5.467904,7.098594,5.253815,5.420998,5.100616,5.315164,6.663280,6.852839,6.780346,...,5.100616,4.727253,4.727253,4.727253,4.727253,4.727253,4.727253,4.991628,4.727253,4.727253

In [9]:
from sklearn.ensemble import RandomForestClassifier

X = df.drop('Diagnosis', axis=1)
y = df['Diagnosis']

Feature_Names = X.columns


# Set up the Random Forest Classifier
clf = RandomForestClassifier()
clf.fit(X, y)

# Get feature importances
importances = clf.feature_importances_

# Sort features based on their importance scores
sorted_indices = np.argsort(importances)[::-1]

# Select the top-k features with the highest importance scores
k=200
selected_features = Feature_Names[sorted_indices[:k]].tolist()

# Create a new DataFrame with the selected features and target variable
new_df = X[selected_features].copy()
new_df['Diagnosis'] = y.values

# Print the new DataFrame
print(new_df.head())

               FAH     SALL4    CIRH1A    LRRIQ1    NCCRP1     STAC2  \
SEQ12179  7.741941  6.627973  7.863526  7.192510  6.179015  6.496228
SEQ12182  7.556161  7.008253  7.651598  7.527644  5.472096  6.291008
SEQ12199  7.664199  6.658601  7.812780  7.194893  5.944415  6.891519
SEQ12196  7.621679  6.665073  7.838578  7.364570  5.884414  6.354898
SEQ12201  7.632255  6.852839  7.794188  7.174439  6.032244  6.225292

              PDP2    FAM47C    ZNF737       MAX  ...    OR5AN1      ASS1  \
SEQ12179  6.923985  5.181797  5.902110  8.290944  ...  4.727253  7.741941
SEQ12182  6.920958  5.102764  6.432256  8.554376  ...  5.102764  7.703333
SEQ12199  7.051831  5.088189  6.035944  8.239862  ...  4.727253  8.255802
SEQ12196  6.950614  4.727253  6.230470  8.337223  ...  4.969556  7.935620
SEQ12201  6.965350  4.727253  6.185253  8.362551  ...  4.991628  8.006660

           FAM71F1  TCTEX1D4    FBXL16      DEDD     MED25    CYP7B1  \
SEQ12179  7.137326  5.978623  6.179015  6.294684  6.747132  8.619088
SEQ12182  6.752568  5.472096  5.704762  6.327954  6.965328  8.831863
SEQ12199  6.780337  5.895303  6.523785  5.895303  7.399271  8.605427
SEQ12196  6.742622  5.813114  6.278728  6.309802  7.146045  8.710867
SEQ12201  6.804965  5.732166  6.225292  6.008458  7.098594  8.465027

             SIDT2  Diagnosis
SEQ12179  7.137326          0
SEQ12182  6.920958          1
SEQ12199  7.369751          0
SEQ12196  7.169553          1
SEQ12201  7.237475          0

[5 rows x 201 columns]

In [10]:
new_df.to_csv("data6.csv")