In [8]:
import pandas as pd
df = pd.read_csv("data0.csv", index_col=0).T
df.to_csv('data1.csv')
df.head()

ensemblID,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000283690,ENSG00000283691,ENSG00000283692,ENSG00000283693,ENSG00000283694,ENSG00000283695,ENSG00000283696,ENSG00000283697,ENSG00000283698,ENSG00000283699
sample_09,90,0,332,728,451,32,351,103,834,1536,...,0,0,1,0,0,2,26,0,1,0
sample_16,145,1,344,920,497,41,197,155,752,1702,...,0,0,1,0,0,3,19,0,0,0
sample_43,167,2,348,843,577,41,225,236,901,1421,...,0,0,4,0,0,3,27,0,4,0
sample_65,187,0,331,739,545,46,170,220,890,1220,...,0,0,3,0,0,1,19,0,3,0
sample_07,155,2,394,885,411,52,209,370,1202,1991,...,0,0,2,0,0,0,26,0,4,0