In [1]:
import pandas as pd

# Specify the file path to your text file
file_path = r'C:\Users\ACER\OneDrive - University of Jaffna\UOJ\Education\Research\Data Sets\GSE160310\smallRNA\GSE160308_human_retina_DR_smallRNA_counts.txt'

# Initialize empty lists to store data
data = []

# Read the text file line by line
with open(file_path, 'r') as file:
    for line in file:
        # Split each line into values using a comma as the delimiter
        values = line.strip().split(',')
        data.append(values)

# Create a DataFrame from the extracted data
df = pd.DataFrame(data)

# # Set the first row as the column headers
df.columns = df.iloc[0]

# # Drop the first row, which contains the column names
df = df[1:]

# Reset the index
df.reset_index(drop=True, inplace=True)

# Display the DataFrame
df
print(df)

df.to_csv('data0.csv', index=False)

0           mirbaseID   sample_01   sample_02  sample_03   sample_04  \
0     hsa-let-7a-2-3p           5           3          3          10
1       hsa-let-7a-3p      958.34     1224.84       1575     3659.66
2       hsa-let-7a-5p  1669011.08  1113228.84  548076.06  1193248.35
3       hsa-let-7b-3p      574.75      608.25      466.5      1315.5
4       hsa-let-7b-5p   452902.16   294703.75  124670.91   287310.08
...               ...         ...         ...        ...         ...
2571    hsa-miR-98-5p    26149.75    16161.25    7975.25    14910.08
2572   hsa-miR-99a-3p         961      1092.5      828.5        1420
2573   hsa-miR-99a-5p    33780.75       28751      10081       21588
2574   hsa-miR-99b-3p      2046.5        1701       1179        2726
2575   hsa-miR-99b-5p    63969.33       45678    31434.5    73796.67

0     sample_05   sample_06  sample_07   sample_08  sample_09  ...  \
0             7          20          3           6          8  ...
1       2647.16      4655.5       2348     2263.66    4187.16  ...
2     861134.44  1259053.95  990696.64  1030404.63  813145.02  ...
3        1095.5     2136.25     867.25       847.5    1182.25  ...
4        207922   321917.33  219048.16   214309.91   213660.5  ...
...         ...         ...        ...         ...        ...  ...
2571    8760.25       16503   12615.42     12886.5    9095.17  ...
2572       1288        2219     1395.5        1359       1783  ...
2573      12593       17682    11582.5     13681.5      16428  ...
2574    1812.33      3658.5     1654.5      1721.5       1683  ...
2575   52620.83    92885.83   48532.83       47724      48183  ...

0      sample_71   sample_72   sample_73   sample_74   sample_75   sample_76  \
0             11          18          52          28          11           8
1        1411.66        2418     4763.16     7100.84        1794         855
2     1406241.55  1042774.47  1599403.33  1464129.38  1841514.27  2021922.24
3         644.75      678.25      1400.5     1289.25      672.75       427.5
4      235585.25   249968.91   418229.58    311276.5   394872.74   415719.49
...          ...         ...         ...         ...         ...         ...
2571       11076    10469.67    14507.67     12643.5     20442.5    16580.17
2572      947.83      1665.5      3449.5      3425.5        1380       847.5
2573       10201     17875.5       35951     33057.5       50529       31281
2574        1172        1089      2896.5      2196.5        1455      1511.5
2575       38003     41766.5       85220    64092.33    58943.33     51020.5

0    sample_77   sample_78   sample_79   sample_80
0           12           3           7           3
1      2926.34         292     2067.34      836.34
2       919517  1456949.88  1760813.07  1536240.56
3       954.75       336.5      883.75         402
4     219300.5   510510.41   314988.49   404629.74
...        ...         ...         ...         ...
2571   7360.25    12935.42    12984.75     10933.5
2572      1562         542      1513.5         717
2573   14614.5       17749       15815     23201.5
2574   1683.83      941.75        1438        1180
2575   50682.5     40686.5     53141.5    45417.83

[2576 rows x 80 columns]

In [2]:
df = pd.read_csv("data0.csv", index_col=0).T
df.head()

mirbaseID,hsa-let-7a-2-3p,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7b-3p,hsa-let-7b-5p,hsa-let-7c-3p,hsa-let-7c-5p,hsa-let-7d-3p,hsa-let-7d-5p,hsa-let-7e-3p,...,hsa-miR-95-3p,hsa-miR-95-5p,hsa-miR-96-3p,hsa-miR-96-5p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
sample_01,5.0,958.34,1669011.08,574.75,452902.16,142.0,203795.00,1128.0,51569.17,336.0,...,13823.00,3.00,178.00,546661.58,84.0,26149.75,961.0,33780.75,2046.50,63969.33
sample_02,3.0,1224.84,1113228.84,608.25,294703.75,107.0,120300.83,513.0,34112.08,327.5,...,10677.92,4.58,192.00,532109.42,116.0,16161.25,1092.5,28751.00,1701.00,45678.00
sample_03,3.0,1575.00,548076.06,466.50,124670.91,79.0,42925.42,688.0,15141.50,239.0,...,9154.00,6.00,120.00,224765.08,192.0,7975.25,828.5,10081.00,1179.00,31434.50
sample_04,10.0,3659.66,1193248.35,1315.50,287310.08,204.5,96194.33,1983.5,35249.75,449.0,...,22962.08,11.25,482.50,347113.67,416.5,14910.08,1420.0,21588.00,2726.00,73796.67
sample_05,7.0,2647.16,861134.44,1095.50,207922.00,227.0,70847.75,1407.0,21116.75,274.0,...,15186.50,6.08,467.75,313103.42,237.5,8760.25,1288.0,12593.00,1812.33,52620.83

In [3]:
df.describe()

mirbaseID,hsa-let-7a-2-3p,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7b-3p,hsa-let-7b-5p,hsa-let-7c-3p,hsa-let-7c-5p,hsa-let-7d-3p,hsa-let-7d-5p,hsa-let-7e-3p,...,hsa-miR-95-3p,hsa-miR-95-5p,hsa-miR-96-3p,hsa-miR-96-5p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
count,79.000000,79.000000,7.900000e+01,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,...,79.000000,79.000000,79.000000,7.900000e+01,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,12.721519,2787.960759,1.260389e+06,1041.149747,294007.589241,214.544304,117772.625570,1289.643418,28147.442025,301.164430,...,16599.959747,7.384430,434.729114,4.732471e+05,239.334304,12787.838987,1740.383671,21194.480886,1894.846709,58562.168228
std,7.778894,1554.701890,3.348985e+05,475.824277,92710.632622,94.060237,49267.559223,504.915863,9951.635706,100.448744,...,5237.376611,4.500208,253.773969,2.534846e+05,143.554715,4932.695702,727.041896,12054.202128,607.081090,16141.507725
min,3.000000,292.000000,5.480761e+05,312.500000,124670.910000,79.000000,42925.420000,383.000000,12266.670000,108.000000,...,5457.080000,0.500000,16.000000,8.609075e+04,30.000000,4730.670000,542.000000,8314.500000,756.000000,27404.000000
25%,7.500000,1466.330000,1.013617e+06,606.000000,228549.955000,149.250000,85456.420000,971.500000,21254.460000,238.500000,...,12956.500000,3.915000,263.580000,3.254424e+05,115.000000,9243.705000,1248.500000,13402.250000,1517.665000,48230.500000
50%,11.000000,2647.160000,1.234320e+06,1022.500000,274106.000000,192.000000,102896.920000,1284.000000,25982.670000,294.000000,...,16008.170000,6.500000,374.330000,4.280391e+05,218.250000,11418.330000,1620.500000,17682.000000,1801.500000,57162.500000
75%,16.500000,3832.580000,1.474052e+06,1312.250000,333406.745000,269.000000,134870.705000,1602.000000,33378.205000,335.665000,...,19818.750000,9.540000,606.665000,5.276342e+05,314.000000,15448.920000,2069.750000,25290.665000,2220.665000,67478.250000
max,52.000000,7100.840000,2.234117e+06,2626.000000,603506.990000,591.000000,274732.580000,2709.500000,60912.750000,716.000000,...,36399.250000,22.830000,1169.500000,1.685386e+06,655.500000,27793.670000,3634.500000,73953.830000,4467.500000,125326.500000

In [4]:
df.dtypes

mirbaseID
hsa-let-7a-2-3p    float64
hsa-let-7a-3p      float64
hsa-let-7a-5p      float64
hsa-let-7b-3p      float64
hsa-let-7b-5p      float64
                    ...
hsa-miR-98-5p      float64
hsa-miR-99a-3p     float64
hsa-miR-99a-5p     float64
hsa-miR-99b-3p     float64
hsa-miR-99b-5p     float64
Length: 2576, dtype: object

In [5]:
df = df.sort_index()
df.to_csv('data1.csv')
df

mirbaseID,hsa-let-7a-2-3p,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7b-3p,hsa-let-7b-5p,hsa-let-7c-3p,hsa-let-7c-5p,hsa-let-7d-3p,hsa-let-7d-5p,hsa-let-7e-3p,...,hsa-miR-95-3p,hsa-miR-95-5p,hsa-miR-96-3p,hsa-miR-96-5p,hsa-miR-98-3p,hsa-miR-98-5p,hsa-miR-99a-3p,hsa-miR-99a-5p,hsa-miR-99b-3p,hsa-miR-99b-5p
sample_01,5.0,958.34,1669011.08,574.75,452902.16,142.0,203795.00,1128.0,51569.17,336.00,...,13823.00,3.00,178.00,546661.58,84.0,26149.75,961.0,33780.75,2046.50,63969.33
sample_02,3.0,1224.84,1113228.84,608.25,294703.75,107.0,120300.83,513.0,34112.08,327.50,...,10677.92,4.58,192.00,532109.42,116.0,16161.25,1092.5,28751.00,1701.00,45678.00
sample_03,3.0,1575.00,548076.06,466.50,124670.91,79.0,42925.42,688.0,15141.50,239.00,...,9154.00,6.00,120.00,224765.08,192.0,7975.25,828.5,10081.00,1179.00,31434.50
sample_04,10.0,3659.66,1193248.35,1315.50,287310.08,204.5,96194.33,1983.5,35249.75,449.00,...,22962.08,11.25,482.50,347113.67,416.5,14910.08,1420.0,21588.00,2726.00,73796.67
sample_05,7.0,2647.16,861134.44,1095.50,207922.00,227.0,70847.75,1407.0,21116.75,274.00,...,15186.50,6.08,467.75,313103.42,237.5,8760.25,1288.0,12593.00,1812.33,52620.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sample_76,8.0,855.00,2021922.24,427.50,415719.49,156.0,207626.25,933.0,38732.50,222.33,...,14260.67,1.25,262.33,930834.67,64.0,16580.17,847.5,31281.00,1511.50,51020.50
sample_77,12.0,2926.34,919517.00,954.75,219300.50,182.0,81279.67,1060.0,17063.67,183.33,...,14291.67,9.00,465.33,291892.08,205.0,7360.25,1562.0,14614.50,1683.83,50682.50
sample_78,3.0,292.00,1456949.88,336.50,510510.41,121.0,274732.58,1489.0,24604.58,108.00,...,5457.08,1.50,16.00,86090.75,30.0,12935.42,542.0,17749.00,941.75,40686.50
sample_79,7.0,2067.34,1760813.07,883.75,314988.49,180.0,122454.17,1591.0,22594.67,253.50,...,16970.75,4.50,297.50,459975.83,102.0,12984.75,1513.5,15815.00,1438.00,53141.50
sample_80,3.0,836.34,1536240.56,402.00,404629.74,97.0,152380.00,756.0,26663.92,209.50,...,9178.50,2.83,107.67,531949.75,47.0,10933.50,717.0,23201.50,1180.00,45417.83

In [6]:
# Get the count of NaN values in each column
nan_counts = df.isnull().sum()

# Sum the NaN counts across all columns
total_nan_count = nan_counts.sum()

# Print the total NaN count
print("Total NaN count:", total_nan_count)

Total NaN count: 0